### ISSUE TITLE
Update source-maps, remove @types/source-map

### ISSUE THREAD

**Issue by jason0x43** [theintern/istanbul-loader#1]
As of at least source-map 0.7.0, TS types are included in the main package.

**Comment by dylans** [comment]
Note that 0.7.0 does introduce some breaking API changes (I found this out the fun way with remap-istanbul).

**Comment by jason0x43** [comment]
The source-maps dependency is updated to 0.6.1 in 444f4ff, which includes typings. Aside from the breaking API changes, the current version of `@types/istanbul-lib-instrument` is using the 0.6.x typings, and there are disagreements there, too.
